### ISSUE TITLE
Unable to figure out how to get live coding in Debian/live coding outside of Linux?

### ISSUE THREAD

**Issue by SugarRayLua** [sharow/lovelive#1]
Hi, @sharow. Lovelive looks very interesting to me as a novice Love2D programming to get real-time feedback as to what the different Love2D commands do. However, I'm having trouble getting it to work. I'm currently trying it in:

Debian 11 (virtual machine)
With Love2d 11.3 installed

I followed the usage advice and am able to bring up a blank (black) Love2d window with:
$love live &

However, when I try to execute the next command:

$ $EDITOR live/app.lua

I get both a broken pipe error with AL library and
Comments about the editor not seeming to be able to parse "app.lua"

Is there a particular editor than I need to set in my linux environment or specific settings I need to tell my editor in linux to be able to use "app.lua" to live code using lovelive?

Also, is it possible to live code using lovelive outside of linux? It would be great to be able to livecode Love2D just from working within a running .love file running solely under Love2D itself (I'm primarily a mobile iOS iPad user and thus cannot utilize ZeroBrane for live coding Love2D on the iPad).

Thanks!

**Comment by sharow** [comment]
Hello.

----

> $ $EDITOR live/app.lua
> 
> I get both a broken pipe error with AL library and
> Comments about the editor not seeming to be able to parse "app.lua"

What is the $EDITOR environment variable set to?
in my case
> $ echo $EDITOR
> emacs

if it's blank, this may help you: https://askubuntu.com/questions/432524/how-do-i-find-and-set-my-editor-environment-variable

> Is there a particular editor than I need to set in my linux environment

No.
you can use any editor or IDE, just open live/app.lua.
fundamentally you don't need deal with $EDITOR or such. open, edit, save , that's it.

----
> Also, is it possible to live code using lovelive outside of linux?

love2d it's self, works fine with OSX/Windows/etc.

I don't have Tablet/Pad thing, so I can't answer for those.

**Comment by SugarRayLua** [comment]
Thank you.
